### ISSUE TITLE
Demo Tribal TANF Error Reports prototype

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#94] opened 2020-08-10 16:37 UTC
**Description:**
Alex P developed a tribal TANF error report prototype. Would be helpful for her to demo for team. Also, could we make the code accessible to the vendors/host in our environment?

**AC:** 

- [ ] Sample acceptance criteria

**Tasks:** 

- [ ] Sample tasks
 

**Open Questions:**

(any clarifying questions in support of the issue)

**Comment by jenewingpierce** [comment] 2021-02-09 22:34
@lfrohlich can we still arrange for this?  This could be useful for the Tribal workshop...

**Comment by amilash** [comment] 2021-07-21 18:38
@dk-ui  seems like this is a duplicate of work you are doing. Can I close it?

**Comment by dk-ui** [comment] 2021-07-21 18:39
@amilash We were able to see this process. This ticket can close

**Comment by amilash** [comment] 2021-07-21 18:58
Closing. Thanks.

**Closed by amilash** 2021-07-21 18:58 UTC
Labels: No longer needed, Research & Design, discussion, triage
