### ISSUE TITLE
As a data analyst I can see my submission history

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1216] opened 2021-08-10 18:49 UTC
**Description** 
As a data analyst, I can access my submission history for a given Quarter/FY.

**Notes**

**AC**
- [ ] Users can determine when a given submission was submitted
- [ ] Users can download all previous versions of the files they've provided
- [ ] Users have insight into summary data for each submission (# of cases, # of errors, etc...)

**Tasks**
- [ ] Design

**Comment by valcollignon** [comment] 2021-11-22 19:07
Duplicate of #1274. Recommend to close @lfrohlich 
CC: @ADPennington @sreedevip @reitermb

**Comment by ADPennington** [comment] 2021-11-23 15:05
agree @valcollignon cc: @lfrohlich

**Comment by valcollignon** [comment] 2021-12-14 16:33
Closed per backlog refinement 12.14.21
CC: @lfrohlich

**Closed by valcollignon** 2021-12-14 16:33 UTC
Labels: Research & Design, DUPE
