### ISSUE TITLE
9/9/21 email update: restage cloud.gov apps

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1309] opened 2021-09-09 12:57 UTC
Please restage apps as laid out in [buildpack ADR](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Architecture%20Decision%20Record/011-buildpacks.md).

**Comment by abottoms-coder** [comment] 2021-09-09 13:12
Duplicate of #1308

**Closed by abottoms-coder** 2021-09-09 13:12 UTC
Labels: DUPE, devops
