### ISSUE TITLE
Create a R & D Roadmap 

### ISSUE THREAD

**Issue by jenewingpierce** [raft-tech/TANF-app#577] opened 2021-01-25 18:16 UTC
Description:

AC:

- [ ] R & D Roadmap is updated and complete 
- [ ] R & D Roadmap is cross-referenced and integrated into Product Roadmap 

Proposed Tasks:

- [ ] Create a roadmap and update multiple drafts based on PM and PO feedback
- [ ] Provide @lfrohlich with annotated artifact samples 
  

DoD:
 - [ ] Documentation: Submitted to QASP 
 - [ ] @lfrohlich has reviewed and signed off

**Comment by kniz-raft** [comment] 2021-01-25 18:33
Duplicate of 577

**Closed** 2021-01-25 18:33 UTC
Labels: research
