### ISSUE TITLE
SPIKE:  File transfer options for Tribal MVP

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#1011] opened 2021-06-09 14:27 UTC
Option 1: Cron job or cf task picks up files, renames them and drops them in a folder in ACF network (not on ACFTitan). TDP Sys admins pick them up and transfer manually to ACFTitan server for processing and storage in TDRS. 

Option 2: Cron job or cf task picks up files nightly, renames them and drops them in an SFTP folder on ACFTitan server to be picked up for processing and storage in TDRS.
 
Option 3: Provide a secure way for tribe data files submitted via TDP  to be accessible by TDP sys admins to pick up and transfer to manually to ACFTitan server  for processing and storage in TDRS.

Success:
Data files are accessible to TDP sys admins (can be seen, downloaded) for processing and storage in TDRS. 

Considerations:
- Needs to be a light lift since this is not our long term direction
- Ideal if files can be transferred automatically to ACFTitan server (removing need to use the UI to download section by section)
- Ideal if files are transferred in a non-zipped folder (structure of folder: Date>>Fiscal Year >> Fiscal Quarter >> [insert files])
- OFA team would benefit from a daily summary report of files submitted and transferred 
- Process for obtaining approval to transfer files from TDP (cloud.gov) to ACFTitan not clear yet. Process for obtaining approval to transfer files to non-ACFTitan server also unclear. 
- Researched options should include detail about the security of the file transfer process.  
- TDP IPT may require updates to docs (e.g. boundary diagram) to reflect this strategy.

**Comment by abottoms-coder** [comment] 2021-06-09 19:01
STT Naming Conventions:
![STT_naming](https://user-images.githubusercontent.com/84722778/121413214-7813a300-c933-11eb-8e29-08a0f85422d9.png)
![tribal_codes](https://user-images.githubusercontent.com/84722778/121413232-7cd85700-c933-11eb-81e8-6ea48d070b31.png)

https://teams.microsoft.com/l/message/19:e92913e3e7d443adb823e6497dff1fb3@thread.skype/1600796602464?tenantId=d58addea-5053-4a80-8499-ba4d944910df&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287&parentMessageId=1600785052682&teamName=TANF%20Data%20Portal%20(OFA)&channelName=Research%20and%20Design&createdTime=1600796602464

Tribal Naming Conventions:
![tribal_codes](https://user-images.githubusercontent.com/84722778/121413232-7cd85700-c933-11eb-81e8-6ea48d070b31.png)

https://teams.microsoft.com/l/message/19:e92913e3e7d443adb823e6497dff1fb3@thread.skype/1600803010240?tenantId=d58addea-5053-4a80-8499-ba4d944910df&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287&parentMessageId=1600785052682&teamName=TANF%20Data%20Portal%20(OFA)&channelName=Research%20and%20Design&createdTime=1600803010240

**Comment by abottoms-coder** [comment] 2021-06-09 19:31
What service account for access to OCIO/NIH production SFTP server? This seems a non-starter.

Acceptance criteria: Daily zip file for data uploaded by Tribe Grantees in last 24 hours stored at a novel URL path within django app. User visible error for no file generated for today. Will have to change the "file object" page to a filename and we can leverage the Grantees' tribe as usage for renaming convention.

Django Admin actions as a possible technical solution for initiating the gathering of files and zipping. 
https://docs.djangoproject.com/en/3.2/ref/contrib/admin/actions/

**Comment by abottoms-coder** [comment] 2021-06-09 19:48
#818 needs to be finished/merged.

**Comment by ADPennington** [comment] 2021-06-09 23:07
couple of other considerations:
- some of Thomas' work involves producing a summary of files submitting for processing in a given day. it's disaggregated by STT, section, and quarter. 
- we may need up to 4 zipped files per day (1 per quarter) (or subfolders within a daily zipped file) because file names only distinguish STT, program, and section. Risk may be low given quarterly reporting schedule, but it is technically possible for an STT to submit files for multiple quarters on the same day. An alternative is to limit the scope of what can be submitted for the purposes of release 2.

**Comment by ADPennington** [comment] 2021-06-15 20:51
> couple of other considerations:
> 
> * some of Thomas' work involves producing a summary of files submitting for processing in a given day. it's disaggregated by STT, section, and quarter.
> * we may need up to 4 zipped files per day (1 per quarter) (or subfolders within a daily zipped file) because file names only distinguish STT, program, and section. Risk may be low given quarterly reporting schedule, but it is technically possible for an STT to submit files for multiple quarters on the same day. An alternative is to limit the scope of what can be submitted for the purposes of release 2.
 updates:

- we agreed during tech sync on 6/11 to include research herein this ticket on proposed solutions:
  -  1-cloud foundry task to pick up files and drop in sftp folder  and 
  - 2-making zipped files available in django. 

*research to include security-related considerations where possible. ADR will be created once one of these solutions is adopted.* 

- I shared team's [answers](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/SiteAssets/TANF%20Data%20Portal%20(OFA)%20Notebook/Dev%20Notes.one#Tribal%20MVP&section-id={3DBB7D3A-694D-4F1C-A656-F907991C1F7D}&page-id={EAAB0897-1A1A-4AE8-93B2-EEE37E043D1F}&end) 🔒 to OCIO's (TDRS IPT team) initial questions re: tribal mvp on 6/14 standing by for next steps. 

- in TDRS IPT meeting on 6/15, we walked through TDRS engineer's process for picking up files in @ttran-hub's sftp dir for processing. it looks like it may be possible for engineer to pickup files from subdirs, so OFA team will test this out with real tribal TANF data when these are ready again for transmission to TDRS database. this will help us continue honing the tech specs for tribal mvp, in the event that the file transfer solution is adopted.

**Comment by ADPennington** [comment] 2021-06-17 13:43
> > couple of other considerations:
> 
> > 
> 
> > * some of Thomas' work involves producing a summary of files submitting for processing in a given day. it's disaggregated by STT, section, and quarter.
> 
> > * we may need up to 4 zipped files per day (1 per quarter) (or subfolders within a daily zipped file) because file names only distinguish STT, program, and section. Risk may be low given quarterly reporting schedule, but it is technically possible for an STT to submit files for multiple quarters on the same day. An alternative is to limit the scope of what can be submitted for the purposes of release 2.
> 
> 
> 
> updates:
> 
> 
> 
> - we agreed during tech sync on 6/11 to include research herein this ticket on proposed solutions:
> 
>   -  1-cloud foundry task to pick up files and drop in sftp folder  and 
> 
>   - 2-making zipped files available in django. 
> 
> 
> 
> *research to include security-related considerations where possible. ADR will be created once one of these solutions is adopted.* 
> 
> 
> 
> - I shared team's [answers](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/SiteAssets/TANF%20Data%20Portal%20(OFA)%20Notebook/Dev%20Notes.one#Tribal%20MVP&section-id={3DBB7D3A-694D-4F1C-A656-F907991C1F7D}&page-id={EAAB0897-1A1A-4AE8-93B2-EEE37E043D1F}&end) 🔒 to OCIO's (TDRS IPT team) initial questions re: tribal mvp on 6/14 standing by for next steps. 
> 
> 
> 
> - in TDRS IPT meeting on 6/15, we walked through TDRS engineer's process for picking up files in @ttran-hub's sftp dir for processing. it looks like it may be possible for engineer to pickup files from subdirs, so OFA team will test this out with real tribal TANF data when these are ready again for transmission to TDRS database. this will help us continue honing the tech specs for tribal mvp, in the event that the file transfer solution is adopted. 

6/17 update: 

We have confirmed via testing that files from subfolders in @Ttran-hub's directory can be picked up by OCIO engineer for processing into TDRS db. This means that subfolders can be pushed into Thomas' sftp directory and picked up w/o anyone needing to remove the files from the subfolders.

**Comment by abottoms-coder** [comment] 2021-06-28 21:22
Added blocked label as I believe Alex is waiting on OCIO for more info on SFTP logins before we proceed with a Django-based solution. Additionally, scope and requirements are unclear for the Django-based solution if we do indeed need 4 zipped files -- in essence, just need a sync for clarification on this ticket.

For self-reference moving forward:
https://pypi.org/project/pyzipper/

**Comment by abottoms-coder** [comment] 2021-07-02 14:31
Per discussion with Alex yesterday, we talked through the points of contention and decided on the following structure for a django-only solution if SFTP access is not granted:

>YYYYMMDD.zip/
>>YYYY-Q1/
>>>file1
>>>file2

>>YYYY-Q2/
>>>file1

Note: Filename will be unique to a STT.

**Comment by ADPennington** [comment] 2021-07-06 20:00
> Per discussion with Alex yesterday, we talked through the points of contention and decided on the following structure for a django-only solution if SFTP access is not granted:
> 
> > YYYYMMDD.zip/
> > > YYYY-Q1/
> > > > file1
> > > > file2
> 
> > > YYYY-Q2/
> > > > file1
> 
> Note: Filename will be unique to a STT.

minor edit below:
>  YYYYMMDD.zip/
> > YYYYMMDD/
> > > YYYY-Q1/
> > > > file1
> > > > file2
> 
> > > YYYY-Q2/
> > > > file1

**Comment by amilash** [comment] 2021-07-07 15:41
As per @abottoms-coder  ready to ticket this work, and still blocked by gaining access/info from Titan team.

**Comment by ADPennington** [comment] 2021-07-14 20:29
@abottoms-coder as of 7/14: service account credentials obtained.

**Closed** 2021-07-20 20:23 UTC
Labels: R2 (Tribal MVP), triage
