### ISSUE TITLE
[Research Recruitment] FRA Research

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3267] opened 2024-11-04 20:11 UTC
**Description:**

Tracker for research recruitment. 
🔐 Original FRA contacts excel sheet/tracker is found on Mattermost / Raft Sharepoint to protect participant identity

**AC:**

- [x] Research recruitment email w/ booking link has been sent 
- [x] Targeted Participants Recruited: **Done**
- [x] Changes to recruitment criteria have been documented if recruitment/target participant pool has been expanded.

| STT | Date | Time | Zoom Link | Scrubbed Transcript/Notes
| --- | --- | --- | --- |--- |
| 1  | Thursday November 14, 2024 | 12:30 – 1:30 EST| [Join Teams](https://teams.microsoft.com/l/meetup-join/19%3ameeting_YTIwYWQ2ZmMtZGNlMi00NWI0LTliYjMtZWFkY2NhYTFhM2I1%40thread.v2/0?context=%7b%22Tid%22%3a%22ecf3b703-3037-4714-9fb7-e24c98f49931%22%2c%22Oid%22%3a%224091e3e3-8561-4b8c-af39-399533cd248c%22%7d) | [P1 Transcript](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/fra-research/fra-mvp-research-plan/p-1)
| 2 | Thursday November 14, 2024 | 4:00 – 5:00 EST | [Join Teams](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ODA0NjA2ODktYjU4YS00YzgwLTgyMTUtZTUxNmZjZDVmY2Fh%40thread.v2/0?context=%7b%22Tid%22%3a%22ecf3b703-3037-4714-9fb7-e24c98f49931%22%2c%22Oid%22%3a%224091e3e3-8561-4b8c-af39-399533cd248c%22%7d) | [P2 Transcript](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/fra-research/fra-mvp-research-plan/p2)
| 3 | Monday November 18, 2024 | 12:00 – 1:00 EST | [Join Teams](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NmVmMzE5NmQtZDdjYS00MzBhLTg3ZmMtMTJkYTAzZTc4Yzdm%40thread.v2/0?context=%7b%22Tid%22%3a%22ecf3b703-3037-4714-9fb7-e24c98f49931%22%2c%22Oid%22%3a%224091e3e3-8561-4b8c-af39-399533cd248c%22%7d) | [P3 Transcript](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/fra-research/fra-mvp-research-)
| 4 | Friday November 22, 2024 | 3:30 – 4:30 EST | [Join Teams](https://teams.microsoft.com/l/meetup-join/19%3ameeting_YzhkYWE0ZGQtMTdhZS00MzQ2LWJhNWMtN2IyM2JmMDJjZGY0%40thread.v2/0?context=%7b%22Tid%22%3a%22ecf3b703-3037-4714-9fb7-e24c98f49931%22%2c%22Oid%22%3a%224091e3e3-8561-4b8c-af39-399533cd248c%22%7d) | [P4 Transcript](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/fra-research/fra-mvp-research-plan/p4)
| 5 | Tuesday December 3, 2024 | 5:00 – 6:00 pm EST | [Join Teams](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZWY1ZjdlMWItNzk1Zi00OTY1LTlkMDMtZjJhMzUzZTllMmE0%40thread.v2/0?context=%7b%22Tid%22%3a%22ecf3b703-3037-4714-9fb7-e24c98f49931%22%2c%22Oid%22%3a%224091e3e3-8561-4b8c-af39-399533cd248c%22%7d) | [P5 Transcript](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/fra-research/fra-mvp-research-plan/p5)

**Supporting Documentation:**

- [Research plan](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/fra-research/fra-mvp-research-plan)

**Comment by lhuxraft** [comment] 2024-11-13 16:53
11/13/2024: Landed two new participants, added a tracker

**Comment by victoriaatraft** [comment] 2024-11-15 15:58
### General Takeaways From Interviews
Providing for situational awareness, transcripts found on gitbook

#### P1 Post Session Takeaways

- Surprised how seamless the one page submission history was. Asked about that did you notice it was on the same page and probably a good thing that the answer was no. It grabs the eye and it just worked. 
- A lot of the assumptions we gone in have proved true so far. We validated the filter ideas of potentially and the needed data and here's where the problem is and the feedback. Sounded like the standalone one could work given additional data, but would be curious with folks who aren't well set up with automation and high quality data processes in house and what reactions we get there.
- The block of text at the top of the excel sheet was a good call out to processing data. -> add a prompt for future sessions, as needed. 
- No fully trained person to replace which is a constant theme across research. 

#### P2 Post Session Takeaways

- Disclosure on the Excel sheet: Nice to have disclosure but it's in the way on the since they use SAS
- Interested in the way the seem to be thinking about the reports. We think they are lumping the supplemental optional with the required one. 
- County administered element is also interesting. Counties don't necessarily do it the same way. There was an impression there was a central office and people were responsible for their own jurisdiction but there may be some variability in the county level like states. 
- We don't know which version of the year is captured in the exit date in the table. Is it Fiscal or Calendar. It was a good callout to be thrown off. 
- People are leaning towards Version A 
 - 3 measures on the work outcomes (exit date, ssn, ?)
 - 1 for secondary school attainment
 - SSN sharing agreement
 - CSV
- tripped up by exit date
- communicate pilot version availability
- UX internal experiment: Can we a csv same a filtered default when opened in excel. Can we save it and send it to each other
- Participants Interested in testing the pilot 

#### P3 Post Session Takeaways

- They will reach out to their IT person and use the original email and set up an appointment 
- People submitting are not those doing the data prep. They are not the people doing the corrections themselves. So having the alternative person will be great. 

#### P4 Post Session Takeaways

- "I'm an impatient person I like stuff to be right" -> commentary and data coding instruction change, potentially miscellaneous 
- They work with a vendor was interesting. 
- The  A/B options for the Error Reports are both is helpful one for the vendor team and one is for us was the first time we encountered. 
- Interested in being talked to again in the future
- Eligibility System STT using depends. There are three main systems tribes use. Three on the state side and three fully custom. No standards for one eligibility system to rule them all. 
- Formats themselves we have a benefit because those are standardized since ACF needs to accept one type of thing, but the way these systems look differs wildly. You get old ones 

#### P5 Post Session Takeaways

- Four other participants  on the call
- They have a streamlined workflow that already checks so the odds of getting the error report is like none
- Still at 100% version A and seemed very impressed with the excel metric
- Similar to past sessions for some individuals and are ahead of the curve process wise. They'd never get errors was familiar.
- Interested hearing about that all new cases are queried against the nataional database. An advanced internal database.
- Correlation with bigger teams have more advanced workflows/systems

@reitermb cc: @klinkoberstar @ADPennington @lfrohlich

**Comment by lhuxraft** [comment] 2024-11-18 16:55
11/18: Update the calendar to additional session

**Comment by lhuxraft** [comment] 2024-11-20 16:56
11/20: Monday session cut short, getting in touch of IT in that STT that are users. Will plan to set up a follow-up session once proper group is identified

**Comment by ADPennington** [comment] 2024-11-20 18:20
@lhuxraft can you check with UX on ticket for the research synthesis for this work? Please tag ticket here 😄

**Comment by victoriaatraft** [comment] 2024-11-20 18:23
> @lhuxraft can you check with UX on ticket for the research synthesis for this work? Please tag ticket here 😄

Just made one as a WIP https://github.com/raft-tech/TANF-app/issues/3297 :)

**Comment by victoriaatraft** [comment] 2024-11-25 19:54
We'll be affinity mapping info collected from the research sessions [here](https://app.mural.co/t/raft2792/m/raft2792/1732564281598/dcead26cbc0379f5f51aba1b56ca4656d64b9ef5) We'll start adding things, but not ready for mapping since we're still conducting sessions/collecting data

cc @lhuxraft @reitermb @klinkoberstar @ADPennington

**Comment by lhuxraft** [comment] 2024-12-02 16:52
12/2: Sending out follow-up emails to land additional sessions

**Comment by lhuxraft** [comment] 2024-12-09 16:53
12/9: Internal working session for affinity. mapping to start

**Closed as completed** 2024-12-16 17:08 UTC
Labels: Research & Design, Refined
