### ISSUE TITLE
SPIKE: Change Managment

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1277] opened 2021-08-27 21:35 UTC
This ticket is intended to capture the required process tasks for deploying to production (and staging) sites so as to not interrupt others.
- Does OCIO/OFA have compliance related mandates for a process we must follow?
- Do we need to re: ATO specs

Approach:
- Raft/Andrew propose ideal approach
- Gain consensus from OFA
- Gain Approval From OFA/OCIO/ ISP

**Comment by abottoms-coder** [comment] 2021-09-14 15:12
- [ ] Review ops manual w/ @ADPennington
- [ ] Consider release 2 vs 3


Urgency/priority is low

**Comment by abottoms-coder** [comment] 2021-09-21 17:58
This appears to be dupe of #480, will close that older ticket out.

**Comment by ADPennington** [comment] 2021-12-27 20:33
Deploying to production requires the following:
- completing production deployment epic (#721)
- updating ATO docs as per #1422

Since this is already being tracked in other issues, closing this ticket.

**Closed by ADPennington** 2021-12-27 20:33 UTC
