### ISSUE TITLE
[DECISION] Does TDP need backups of the data files that it will store in S3? RDS?

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#798] opened 2021-03-29 15:12 UTC
## Context 

Cloud.gov has information about how to back up files in S3, but does not provide automated backups out of the box: https://cloud.gov/docs/services/s3/#backup-and-retention

## Follow-on decision

If TDP needs backups of the data files that it will store in S3, should the backup scheme be in place before Go Live, or can it be set up after Go Live?

## Initial thoughts on process

The OFA Tech Lead should be part of this decision making process! Let's wait til she's back to decide. 

Our decision shouldn't hold us back from moving the Contingency Plan forward. Would be an enhancement to the plan. :sunglasses:

As per @ADPennington 
- Yes we need backups
- backups retention is limited as per SORN
- no rqs for RDS backups
- Requirement comes from "SORN" spec. See details below.

**Comment by alexsoble** [comment] 2021-04-07 17:04
Discussed with @ADPennington — this seems like it could be valuable in the future. We think the team could potentially implement this post ATO, and potentially even post MVP as well — needs discussion!

**Comment by abottoms-coder** [comment] 2021-07-22 18:47
https://www.cloudsavvyit.com/7782/how-to-backup-an-s3-bucket-and-why-youd-even-want-to/

It seems that the venn diagram of backups and versioning is just a circle so this might just be a duplicate of implementing versioning as in #1007 

However, I don't imagine our data quantities will grow into the terabytes so this next one might be a moot point by setting the lifecycle rule of transitioning ancient files from S3 to Glacier is worthy of discussion:
https://cloudacademy.com/blog/amazon-s3-vs-amazon-glacier-a-simple-backup-strategy-in-the-cloud/

**Comment by ADPennington** [comment] 2021-07-26 22:14
adding a little context (some of which includes 7/23 tech sync discussion)--
 
- backup parameters for TDP are subject to the [SORNs](https://www.federalregister.gov/documents/2015/04/02/2015-07440/privacy-act-of-1974-system-of-records-notice) for [Tribal TANF](https://www.federalregister.gov/d/2015-07440/p-221) and [TANF (including SSP)](https://www.federalregister.gov/d/2015-07440/p-276). The following language re: data retention and disposal applies specifically to TANF and SSP data; Tribal TANF has fewer constraints for now:
 
> The data transmitted by a State for a fiscal quarter are backed up after the initial processing of the data. **The backed-up version of the data is kept only for a period of 30 days**. The data transmitted by the States for a fiscal quarter, after processing and acceptance, are pooled to create a national database for the quarter. **The national database is stored for up to 24 months after the end of the fiscal year.** Afterwards, the database is copied to a compact disc, and the original data are erased. **The data on the compact disc is securely maintained by ACF for up to 20 years** in order to facilitate research on caseload trends, changes in the characteristics of TANF recipients, or other pertinent research. The eventual disposal of the data will be by means of physical destruction of the CD's containing the data. The Office of Information Systems of the Office of Administration and OFA, ACF, are responsible for the retention and disposal of the data system
 
- the 30-day retention period seems to apply to raw files to be stored in S3. This language does not specify disposal reqs for these backups.  This may have implications on download capabilities for users  (e.g. cant download file 31 days post-submission). 
- the 24-month retention period seems to apply to parsed data to be stored in the RDS. 
- the 20-year retention period and disposal reqs seems to apply to the cd copy of the database (that starts after the 24m retention period). 
 
- Other considerations:
  - accidental deletion of the data in the buckets/RDS is still possible, but per AB, risk fairly low--especially since only a couple of people will have the ability to access the prod buckets. 
  - other than the cd, no other backups mentioned in the SORN re: parsed data. Per cloudgov: automatic [backup](https://cloud.gov/docs/services/relational-database/#backups) of RDS for 14 days. [Manual backups](https://cloud.gov/docs/services/relational-database/#backups) are also possible, but setup needed. OFA would like snapshots (e.g. taken every 45 days starting around due date for 1st qtr  data). 
  - since SORN limits benefits of versioning, could we generate a report that compares current/most recent versions at the point of re-upload/re-submission?
 
- Suggestions for updating the SORN:
  - Longer raw file retention period -- Retain most recent version of file for 2 years. This helps ensure that the file is available through the final OFA data publication for the fiscal year (e.g. > 1 yr between due date for first qtr of data and final publication). 
  - Longer RDS data retention period -- 5 years improves potential for report features
  - Use alternative, modern long-term media storage options; and specify disposal options for both raw and parsed data
  - Bring Tribal TANF into alignment w/ TANF and SSP. 

cc: @lfrohlich @ttran-hub

**Comment by amilash** [comment] 2021-07-27 15:39
Next Steps:
S3: Lets scope tickets for the work based on the SORN Spec - @abottoms-coder 
RDS: Digit + Dev needs to discuss approach and desires and specs. They are not bound by reqs for this one, its more a matter of need/preference.

**Comment by amilash** [comment] 2021-07-27 15:41
Related to Resubmission

**Comment by ADPennington** [comment] 2021-08-10 17:26
OFA will have a meeting colleagues in OPRE to discuss SORN update process. dev work relevant to staying in compliance w/ existing SORN can be punted to release 3 priority.  cc: @lfrohlich @ttran-hub @amilash

**Comment by valcollignon** [comment] 2022-01-11 16:28
Closing per backlog refinement 1.11.22
CC: @ADPennington @lfrohlich

**Closed by valcollignon** 2022-01-11 16:28 UTC
Labels: Epic, discussion, Blocked, triage
