### ISSUE TITLE
10 day account deactivation warning 

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2697] opened 2023-09-06 19:57 UTC
10 day account deactivation warning email is missing an href 
![image](https://github.com/raft-tech/TANF-app/assets/28515874/ef87e006-7191-403a-95f1-b47e9994df4e)

## Description

The 10 day deactivation warning includes a button (styled link) to TDP that's missing an href to the relevant TDP environment. Other cadences of warning don't seem to have the same issue.

**Comment by elipe17** [comment] 2024-05-24 17:43
Closing after async discussion with @reitermb. Confirmed that `href` is included in the generated html for the email. Verified `href` is present locally via the console, via gmail, and via outlook. All links routed to the correct page in TDP. The only oddity was that SendGrid seems to be obscuring the true URL, see below.

```html
<p><a class=3D"button" href=3D"https://u35556689.ct.sendgrid.net/ls/cli=
ck?upn=3Du001.iSvXeDALry182rNz3Ht0ziv0HPxvdRMIqulGqr6B1az3f78GemIfL0Xzojzt9=
Y7PMD8-_28iqB4CdAs82QkjG1SNQTqbFGuBIh1tsNbaOUFsZXQTLacOVoDzv1YeMBqYs-2B0MRh=
XYzytl4CGuDG9Lrg5tl-2Fvm9Skf-2Be6dbz8ji5pp7PcpJx23IiB6sSD7giY228nt38sy3H1Yl=
hy7yFvAr3s1NR-2FLd6TMcuHhVXwTp5LnzQI-2FZiBA-2BEzYzbKfp7unzAoNnIPy701eW8VVNz=
jxsKwNXRg-3D-3D"
    style=3D"background-color:#336a90;border-radius:4px;color:#ffffff;displ=
ay:inline-block;font-family:sans-serif;font-size:18px;font-weight:bold;line=
-height:60px;text-align:center;text-decoration:none;width: auto; padding-le=
ft: 24px; padding-right: 24px;-webkit-text-size-adjust:none;">Sign in to ke=
ep your account active</a></p>
```

**Closed as completed by elipe17** 2024-05-24 17:43 UTC
Labels: bug, dev, Refined
